spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product-management
    username: root
    password: secret
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect